spring.data.mongodb.uri=mongodb+srv://expensetrackx_user:AvanishExpense09@cluster1.415pmio.mongodb.net/?appName=Cluster1
spring.data.mongodb.database=expense_tracker
server.port=8081
spring.main.allow-bean-definition-overriding=true
